import React from "react";
import { Card, Col, Icon, Row } from "antd";
import styled from "styled-components";
import BigContainer from "./BigContainer";

const MyIcon = Icon.createFromIconfontCN({
  scriptUrl: "//at.alicdn.com/t/font_1211681_4bz2eiak9y2.js", // generated by iconfont.cn
});

function Iconfont(props: { type: string }) {
  return <MyIcon type={props.type} style={{marginRight: "8px"}}/>;
}

interface Feature {
  icon: string;
  title: string;
  description: string;
}

const features = [
  {
    icon: "iconlunwentimu",
    title: "更好的论文阅读和分享体验",
    description: "我们的设计都是为了您能够更加享受阅读论文的过程和更好的交流。",
  },
  {
    icon: "iconxuesheng",
    title: "为学生设计",
    description: "我们由大学生组成的设计团队切身明白同学们的痛点，并对症下药，达到事半功倍的效果。以出神入化之功，收出类拔萃之效。",
  },
  {
    icon: "iconblockchain",
    title: "基于区块链的知识产权保护",
    description: "我们使用屡获殊荣的ChainStore为区块链存储解决方案，确保您在分享论文的同时，不需要担心知识产权的问题。",
  }, {
    icon: "iconRESPONSIVEDESIGN",
    title: "响应式设计",
    description: "我们在此项目再次使用了受到广泛好评的UI解决方案，并融入团队自己对响应式和UI交互的理解，确保您不仅能在大屏幕设备上高效率地使用本项目，还能出门在外也能随时随地阅读论文，和朋友们互动。",
  },
] as Feature[];


function CardFeature(props: { feature: Feature }) {
  const {icon, title, description} = props.feature;
  return <Card title={<span><Iconfont type={icon}/>{title}</span>}
               style={{height: "220px"}}
  >
    {/*<h4>{x.title}</h4>*/}
    <span>{description}</span>
  </Card>;
}

const FeatureContainer = styled.div`
  height: 220px;
  svg {
    width: 48px;
    height: 48px;
  }

  h3 {
    padding: 8px;
  }

  max-width: 400px;
  margin-left: auto;
  margin-right: auto;

  padding: 16px;

  //:hover {
  //  transform: scale(1.05);
  //  border: 1px solid #019BF0;
  //  cursor: initial;
  //  //background: #019BF0;
  //  //color: #ECECEC;
  //}
  //
  //transition: all 0.3s ease-in-out;
`;

function StandardFeature(props: { feature: Feature }) {
  const {icon, title, description} = props.feature;
  return <FeatureContainer>
    <div style={{textAlign: "center"}}>
      <MyIcon type={icon}/>
      <h3>{title}</h3>
      {/*<div style={{ textAlign: "left" }}>*/}
        <small>{description}</small>
      {/*</div>*/}
    </div>
  </FeatureContainer>;
}

interface Props {

}

export default function Features(props: Props) {
  return <div>
    <div style={{paddingTop: "20px", paddingBottom: "40px", backgroundColor: "#ffffff"}}>
      <BigContainer title={"系统特性"}>
        <Row style={{maxWidth: "1500px", marginLeft: "auto", marginRight: "auto"}}>
          {features.map((x, i) => (
            <Col xs={24} sm={12} lg={6} key={i}>
              <StandardFeature feature={x}/>
            </Col>
          ))
          }
        </Row>
      </BigContainer>
    </div>
  </div>;
}
